### PR TITLE
Update OS X prereqs for new icu4c

### PR DESCRIPTION
**Pull request by cadeParade**
icu4c is now at 50.1; I've updated the README to reflect this when symlinking the lib dirs

### CODE REVIEW

**Comment by nova77** [comment]
I think _brew_ now allows you to automatically link to the newest version with:

``` bash
brew link icu4c --force
```

**Comment by erikfrey** [comment]
@cadeParade thanks very much for pointing this out.

@nova77 Can you confirm that approach works?

**Comment by jasonm** [comment]
I submitted the pull under @cadeparade's account - I can confirm that using `brew link icu4c --force` works on my machine.  (OSX 10.8.3, gcc-4.2.1, xcode 4.6, python 2.7.2)

**Comment by nova77** [comment]
@erikfrey I can confirm it does work on my machine too (OSX 10.8.3, gcc-4.2.1, python 2.7.2).

**Comment by erikfrey** [comment]
Okay, I'll update the README accordingly - thanks guys.

**Pull request closed without merging**
